[package]
name = "async-cell-lock"
version = "0.1.2-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
once_cell = { version = "1" }
parking_lot = "0.11"
tokio = { version = "1", features = ["parking_lot", "sync"] }
