[package]
name = "async-cell-lock"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

[dependencies]
once_cell = { version = "1" }
tokio = { version = "1", features = ["parking_lot", "sync"] }
